---
title: 'Analysis Draft: 2018 r/feminism Study'
author: "Tyler Simko"
date: "10/23/2019"
output: pdf_document
---

```{r, warning=FALSE}
library(MASS)
library(ggplot2)
reddit <- read.csv("../data/r-feminism-study-data-merged-10.17.2019.csv", 
                   stringsAsFactors = FALSE)

colnames(reddit)
table(reddit$treatment)
```

## Overall participation

```{r}
comments.mod <- glm.nb(comments_2_weeks ~ treatment, data=reddit)
summary(comments.mod)$coefficients

comments.mod.4 <- glm.nb(comments_4_weeks ~ treatment, data=reddit)
summary(comments.mod.4)$coefficients

comments.mod.8 <- glm.nb(comments_8_weeks ~ treatment, data=reddit)
summary(comments.mod.8)$coefficients

## results
res <- data.frame(rbind(summary(comments.mod)$coefficients[2,],
                        summary(comments.mod.4)$coefficients[2,],
                        summary(comments.mod.8)$coefficients[2,]))

res$period <- c("2 weeks", "4 weeks", "8 weeks")
colnames(res) <- c("est", "se", "z", "p", "period")

ggplot(res, aes(x = period, y = est)) + 
  geom_point(size = 2) + 
  geom_errorbar(aes(ymin = est - 1.96*se, ymax = est + 1.96*se), width = 0.2) + 
  geom_hline(yintercept = 0, lty = "dashed", color = "#A36D90") + theme_bw() + 
  xlab("Time after Treatment") + ylab("ATE on # of Comments")
```

## Survey measures

```{r}
inclusion.mod <- lm(community_closeness ~ treatment, 
                      data=subset(reddit, completed_survey=="True"))
summary(inclusion.mod)$coefficients

reddit$identify_feminist <- ifelse(reddit$identify_feminist == "Yes", 1,
                                   ifelse(reddit$identify_feminist == "No", -1,
                                          ifelse(reddit$identify_feminist == "Undecided", 0, NA)))

identify.mod <- lm(identify_feminist ~ treatment, 
                      data=subset(reddit, completed_survey=="True"))
summary(identify.mod)$coefficients
```